### PR TITLE
Upgrade to Angular 11 and MSAL 2

### PR DESCRIPTION
**Pull request by tymathis**
I did an upgrade on this project for a demo presentation. It was very difficult to find an upgraded version with MSAL 2 and AD B2C.

### CODE REVIEW

**Comment by derisen** [comment]
@tymathis thank you very much for this effort! A similar sample is coming along [here](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial) as well. 

@jasonnutter do we want to upgrade this repo or keep it same as reference for v1 usage?

**Comment by jasonnutter** [comment]
For now, we'd like to keep this sample on v1, since we will have a separate v2 sample. You can an existing MSAL Angular v2 B2C sample here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-b2c-sample

**Comment by tymathis** [comment]
Hi Guys,

I am happy to help. I also have some notes on setting up an azure function
that pulls back the claims from the current user. I think it would be cool
to have a template for a completely serverless solution using azure
functions with entity framework and azure databases.

Thanks,
Ty

**Comment by derisen** [comment]
@tymathis we will keep this repo as it is for reference, but thank you very much for the effort regardless!

Regarding a serverless solution, I think you might find [this sample](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/4-Deployment/2-deploy-static) useful. We would love any feedback, and feel free to make a suggestion there.

**Pull request closed without merging**
